version: "3"
services:
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ocean
      LANG: C.UTF-8
    volumes:
      - ./install/db_init:/docker-entrypoint-initdb.d/
    restart: unless-stopped
    privileged: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
  redis:
    image: redis:latest
    container_name: redis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    restart: unless-stopped
    privileged: true
    command: redis-server --requirepass ${REDIS_PASSWORD}
  web:
    build:
      context: .
      dockerfile: ./install/docker/ocean_web.Dockerfile
    image: ocean_web:v1
    ports:
      - "8080:8080"
    container_name: web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/ocean_ctf:/opt/ocean_ctf
    depends_on:
      - db
      - redis
    working_dir: /opt/ocean_ctf
    command: uwsgi --http :8080 -w main:app --enable-threads

